# Generated by Django 2.2.2 on 2019-07-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpic', models.ImageField(height_field=40, upload_to='', width_field=30)),
                ('cname', models.CharField(max_length=50)),
                ('cdetails', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ldetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lpic', models.ImageField(height_field=40, upload_to='', width_field=30)),
                ('lname', models.CharField(max_length=50)),
                ('ldetails', models.CharField(max_length=500)),
            ],
        ),
    ]
