# Generated by Django 2.2.2 on 2019-07-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_auto_20190701_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cdetails',
            old_name='cname',
            new_name='name_text',
        ),
        migrations.RemoveField(
            model_name='cdetails',
            name='cdetails',
        ),
        migrations.RemoveField(
            model_name='cdetails',
            name='cpic',
        ),
    ]
