# Generated by Django 2.2.2 on 2019-07-01 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_auto_20190701_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdetails',
            name='name_text',
        ),
    ]
