# Generated by Django 2.2.2 on 2019-07-01 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_remove_cdetails_name_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdetails',
            name='cdet',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cdetails',
            name='cname',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cdetails',
            name='cpics',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/images/'),
            preserve_default=False,
        ),
    ]
