# Generated by Django 2.2.2 on 2019-07-03 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0005_auto_20190701_1436'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ldetails',
            new_name='ldetailss',
        ),
    ]
