# Generated by Django 2.2.2 on 2019-07-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0006_auto_20190703_1448'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ldetailss',
            new_name='ldetails',
        ),
    ]
