# Generated by Django 2.2.2 on 2019-07-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0007_auto_20190703_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdetails',
            name='cpics',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='ldetails',
            name='lpic',
            field=models.ImageField(upload_to=''),
        ),
    ]
