# Generated by Django 2.2.3 on 2019-07-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0010_auto_20190705_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdetails',
            name='cpics',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
